name: Continuous Deploy
on: [push]
jobs:
    buildAndTest:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install Dependencies
              run: yarn
            - name: Build
              run: yarn build-lib
            - name: Test
              run: npm publish
